import copy
from datetime import datetime, timezone

import discord
from redbot.core import commands


class _StaleEventChannel(Exception):
    """Raised when Discord confirms that an event's channel was deleted."""


class ScheduleListeners:
    """
    Listeners and reaction handling for the Schedule cog.

    Reaction events are serialized per guild by ``_event_lock``. The lock is
    deliberately held while the event action runs, but Config contexts are
    only opened for the short read/write operations around Discord HTTP calls.
    This prevents two reactions from overwriting attendee changes and avoids
    a Config lock being held while ``_share_schedule`` reads or writes Config.
    """

    REMINDER_WINDOW_SECONDS = 30 * 60
    REMINDER_COOLDOWN_SECONDS = 60 * 60
    EVENT_REACTIONS = {"✅", "❗", "📢"}

    @commands.Cog.listener()
    async def on_raw_reaction_add(self, payload: discord.RawReactionActionEvent):
        """Handle a reaction added to a scheduled event message."""
        await self._handle_reaction(payload, "add")

    @commands.Cog.listener()
    async def on_raw_reaction_remove(self, payload: discord.RawReactionActionEvent):
        """Handle a reaction removed from a scheduled event message."""
        await self._handle_reaction(payload, "remove")

    @commands.Cog.listener()
    async def on_raw_message_delete(self, payload: discord.RawMessageDeleteEvent):
        """Prune a schedule immediately when its message is deleted."""
        if payload.guild_id is None:
            return
        guild = self.bot.get_guild(payload.guild_id)
        if guild is None:
            return
        async with self._event_lock(payload.guild_id):
            await self._delete_event(guild, str(payload.message_id))

    @commands.Cog.listener()
    async def on_raw_bulk_message_delete(
        self, payload: discord.RawBulkMessageDeleteEvent
    ):
        """Prune all schedules covered by a bulk message deletion event."""
        if payload.guild_id is None or not payload.message_ids:
            return
        guild = self.bot.get_guild(payload.guild_id)
        if guild is None:
            return
        async with self._event_lock(payload.guild_id):
            async with self.config.guild(guild).scheduled_events() as events:
                for message_id in payload.message_ids:
                    events.pop(str(message_id), None)

    @commands.Cog.listener()
    async def on_raw_thread_delete(self, payload: discord.RawThreadDeleteEvent):
        """Prune schedules when a whole forum post is deleted."""

        guild = self.bot.get_guild(payload.guild_id)
        if guild is None:
            return
        async with self._event_lock(payload.guild_id):
            async with self.config.guild(guild).scheduled_events() as events:
                for message_id, event_data in list(events.items()):
                    if isinstance(event_data, dict) and str(event_data.get("channel_id")) == str(payload.thread_id):
                        events.pop(message_id, None)

    async def _handle_reaction(
        self, payload: discord.RawReactionActionEvent, action: str
    ):
        """Process one schedule reaction while holding its guild event lock."""
        if action not in {"add", "remove"} or payload.guild_id is None:
            return

        emoji = str(payload.emoji)
        # Raw events are emitted for every emoji on a message, not just ours.
        if emoji not in self.EVENT_REACTIONS:
            return
        # Reminder and share reactions are one-shot actions. A remove event
        # for either one is generated by our own cleanup and needs no handling.
        if action == "remove" and emoji != "✅":
            return

        guild = self.bot.get_guild(payload.guild_id)
        if guild is None:
            return

        # Our own initial reactions can produce raw events too. Skip them
        # without fetching a member.
        bot_user = getattr(self.bot, "user", None)
        if bot_user is not None and payload.user_id == getattr(bot_user, "id", None):
            return

        event_key = str(payload.message_id)
        lock = self._get_event_lock(payload.guild_id)
        async with lock:
            event_data = await self._load_event(guild, event_key)
            if not event_data:
                return

            # A reaction payload for a different channel cannot belong to this
            # event. Reject it before any member or message fetch.
            configured_channel_id = event_data.get("channel_id")
            if configured_channel_id is not None and str(configured_channel_id) != str(
                payload.channel_id
            ):
                return

            try:
                channel = await self._fetch_event_channel(payload.channel_id)
            except _StaleEventChannel:
                await self._delete_event(guild, event_key)
                return
            if channel is None:
                return

            try:
                message = await channel.fetch_message(payload.message_id)
            except discord.NotFound:
                await self._delete_event(guild, event_key)
                return
            except discord.Forbidden as exc:
                self._log_http_error(
                    "fetch schedule message",
                    exc,
                    guild_id=payload.guild_id,
                    channel_id=payload.channel_id,
                    message_id=payload.message_id,
                )
                return
            except discord.HTTPException as exc:
                if getattr(exc, "status", None) == 404:
                    await self._delete_event(guild, event_key)
                    return
                self._log_http_error(
                    "fetch schedule message",
                    exc,
                    guild_id=payload.guild_id,
                    channel_id=payload.channel_id,
                    message_id=payload.message_id,
                )
                return

            # Cards created by older versions exposed reminder/share reactions.
            # Clear those controls the next time a member interacts with the
            # card, while retaining the legacy handlers below for compatibility.
            if emoji == "✅" and not event_data.get("private_controls"):
                if await self._clear_legacy_control_reactions(message):
                    event_data["private_controls"] = True
                    await self._save_event(guild, event_key, event_data)

            if self._event_status(event_data) != "active":
                # Completed and cancelled events remain visible for history,
                # but their reactions must not mutate or notify anything.
                if action == "add":
                    await self._remove_reaction(message, payload.emoji, payload.user_id)
                return

            # Once an event has started, the lobby is closed. Existing
            # attendees may still remove their reaction, but a new join would
            # create a misleading attendee list.
            if (
                emoji == "✅"
                and action == "add"
                and self._as_int(event_data.get("start_timestamp"), 0)
                <= int(datetime.now(timezone.utc).timestamp())
            ):
                await self._remove_reaction(message, payload.emoji, payload.user_id)
                return

            if emoji == "❗" and action == "add":
                # The organizer id is available in Config, so unauthorized
                # users never need a member fetch just to be rejected.
                if not self._same_id(payload.user_id, event_data.get("organizer_id")):
                    await self._remove_reaction(message, payload.emoji, payload.user_id)
                    return

                user = await self._fetch_member(guild, payload.user_id)
                if user is not None and getattr(user, "bot", False):
                    return
                await self._handle_reminder(
                    guild,
                    message,
                    event_data,
                    event_key,
                    user or payload.user_id,
                    payload.emoji,
                )
                return

            # Attendance and sharing need a user object for state changes or
            # user-facing confirmation. Fetch it only after the message has
            # been confirmed as a known event and its emoji is known.
            user = await self._fetch_member(guild, payload.user_id)
            if user is None:
                return
            if getattr(user, "bot", False):
                return

            if emoji == "✅":
                await self._handle_attendance(
                    guild, message, event_data, event_key, user, action, payload.emoji
                )
            elif emoji == "📢" and action == "add":
                # _share_schedule is intentionally called inside the event
                # lock. It does Config operations after its Discord HTTP call
                # and does not acquire this lock again.
                await self._share_schedule(
                    guild,
                    user,
                    message,
                    event_data,
                    remove_reaction_after_action=True,
                )

    async def _clear_legacy_control_reactions(self, message):
        """Remove private-control reactions left by pre-separation cards."""

        clear_reaction = getattr(message, "clear_reaction", None)
        if not callable(clear_reaction):
            return False
        for emoji in ("❗", "📢"):
            try:
                await clear_reaction(emoji)
            except discord.NotFound:
                return False
            except (discord.Forbidden, discord.HTTPException) as exc:
                self._log_http_error(
                    "clear legacy schedule reaction",
                    exc,
                    message_id=getattr(message, "id", None),
                    emoji=emoji,
                )
                return False
        return True

    def _get_event_lock(self, guild_id: int):
        """Return the per-guild event lock supplied by the cog."""
        return self._event_lock(guild_id)

    async def _load_event(self, guild: discord.Guild, event_key: str):
        """Load an event snapshot without keeping Config open during I/O."""
        events = await self.config.guild(guild).scheduled_events()
        event_data = events.get(event_key) if events else None
        return copy.deepcopy(event_data) if event_data else None

    async def _save_event(self, guild: discord.Guild, event_key: str, event_data: dict):
        """Persist an event snapshot in a short-lived Config context."""
        async with self.config.guild(guild).scheduled_events() as events:
            if event_key in events:
                events[event_key] = copy.deepcopy(event_data)

    async def _delete_event(self, guild: discord.Guild, event_key: str):
        """Remove a schedule whose channel or message has gone away."""
        async with self.config.guild(guild).scheduled_events() as events:
            events.pop(event_key, None)

    async def _fetch_event_channel(self, channel_id: int):
        """Resolve the event channel and handle Discord HTTP errors."""
        channel = None
        get_channel = getattr(self.bot, "get_channel", None)
        if get_channel is not None:
            channel = get_channel(channel_id)
        if channel is not None:
            return channel

        fetch_channel = getattr(self.bot, "fetch_channel", None)
        if fetch_channel is None:
            return None
        try:
            return await fetch_channel(channel_id)
        except discord.NotFound as exc:
            self._log_http_error("fetch schedule channel", exc, channel_id=channel_id)
            raise _StaleEventChannel from exc
        except discord.Forbidden as exc:
            self._log_http_error(
                "fetch schedule channel", exc, channel_id=channel_id
            )
            return None
        except discord.HTTPException as exc:
            if getattr(exc, "status", None) == 404:
                raise _StaleEventChannel from exc
            self._log_http_error(
                "fetch schedule channel", exc, channel_id=channel_id
            )
            return None

    async def _fetch_member(self, guild: discord.Guild, user_id: int):
        """Use the member cache first, then fetch only when it is needed."""
        get_member = getattr(guild, "get_member", None)
        if get_member is not None:
            member = get_member(user_id)
            if member is not None:
                return member

        fetch_member = getattr(guild, "fetch_member", None)
        if fetch_member is None:
            return None
        try:
            return await fetch_member(user_id)
        except discord.NotFound:
            return None
        except discord.Forbidden as exc:
            self._log_http_error("fetch reacting member", exc, user_id=user_id)
            return None
        except discord.HTTPException as exc:
            if getattr(exc, "status", None) == 404:
                return None
            self._log_http_error("fetch reacting member", exc, user_id=user_id)
            return None

    async def _handle_attendance(
        self,
        guild: discord.Guild,
        message: discord.Message,
        event_data: dict,
        event_key: str,
        user: discord.Member,
        action: str,
        emoji,
    ):
        """Apply join/leave state, update the message, and then persist it."""
        attendees = list(event_data.get("attendees") or [])
        player_limit = self._as_int(event_data.get("player_limit"), 0)
        user_id = user.id

        if action == "add":
            if user_id in attendees:
                return
            if len(attendees) >= player_limit:
                await self._remove_reaction(message, emoji, user)
                await self._safe_dm(
                    user,
                    "This schedule's lobby is full.",
                    "send full-lobby DM",
                )
                return
            attendees.append(user_id)
        elif action == "remove":
            if self._same_id(user_id, event_data.get("organizer_id")):
                try:
                    await message.add_reaction(emoji)
                except discord.NotFound:
                    await self._delete_event(guild, event_key)
                except discord.Forbidden as exc:
                    self._log_http_error(
                        "restore organizer reaction", exc, message_id=message.id
                    )
                except discord.HTTPException as exc:
                    self._log_http_error(
                        "restore organizer reaction", exc, message_id=message.id
                    )
                return
            if user_id not in attendees:
                return
            attendees.remove(user_id)
        else:
            return

        event_data["attendees"] = attendees
        try:
            await self._update_embed(message, event_data)
        except discord.NotFound:
            await self._delete_event(guild, event_key)
            return
        except discord.Forbidden as exc:
            self._log_http_error(
                "update schedule message", exc, message_id=message.id
            )
            return
        except discord.HTTPException as exc:
            if getattr(exc, "status", None) == 404:
                await self._delete_event(guild, event_key)
                return
            self._log_http_error(
                "update schedule message", exc, message_id=message.id
            )
            return

        await self._save_event(guild, event_key, event_data)

    async def _handle_reminder(
        self,
        guild: discord.Guild,
        message: discord.Message,
        event_data: dict,
        event_key: str,
        organizer,
        emoji,
    ):
        """Send one organizer-triggered reminder within the upcoming window."""
        now = int(datetime.now(timezone.utc).timestamp())
        start_timestamp = self._as_int(event_data.get("start_timestamp"), 0)
        seconds_until_start = start_timestamp - now

        # A reminder is useful only during the 30 minutes before the event,
        # and only while the event is still upcoming. This prevents old
        # schedule messages from being used as an unlimited reminder button.
        if not 0 <= seconds_until_start <= self.REMINDER_WINDOW_SECONDS:
            await self._remove_reaction(message, emoji, organizer)
            return

        last_reminder = self._as_int(
            event_data.get(
                "last_reminder_timestamp",
                event_data.get("last_reminded_timestamp", 0),
            ),
            0,
        )
        if last_reminder and now - last_reminder < self.REMINDER_COOLDOWN_SECONDS:
            await self._remove_reaction(message, emoji, organizer)
            if organizer is not None:
                remaining = max(
                    1,
                    (self.REMINDER_COOLDOWN_SECONDS - (now - last_reminder) + 59)
                    // 60,
                )
                await self._safe_dm(
                    organizer,
                    f"A reminder for this schedule was already sent. Please try again in about {remaining} minute(s).",
                    "send reminder cooldown DM",
                )
            return

        # Reserve the reminder before performing HTTP calls. The event lock
        # serializes reactions in this process and the persisted timestamp
        # prevents a second process from repeatedly notifying attendees.
        event_data["last_reminder_timestamp"] = now
        await self._save_event(guild, event_key, event_data)

        game_title = str(event_data.get("game_title") or "The Game")
        reminder_text = (
            f"**Reminder for {game_title}!**\n"
            f"The game is starting <t:{start_timestamp}:F> (<t:{start_timestamp}:R>)!"
        )
        sent_count = 0
        failed_count = 0
        for attendee_id in list(event_data.get("attendees") or []):
            member = await self._fetch_member(guild, attendee_id)
            if member is None:
                failed_count += 1
                continue
            try:
                await member.send(reminder_text)
                sent_count += 1
            except discord.Forbidden as exc:
                failed_count += 1
                self._log_http_error("send reminder DM", exc, user_id=attendee_id)
            except discord.NotFound as exc:
                failed_count += 1
                self._log_http_error("send reminder DM", exc, user_id=attendee_id)
            except discord.HTTPException as exc:
                failed_count += 1
                self._log_http_error("send reminder DM", exc, user_id=attendee_id)

        channel_reminder_sent = False
        try:
            await message.channel.send(
                f"**Reminder for all participants of '{game_title}'!** "
                f"The game starts <t:{start_timestamp}:R>.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
            channel_reminder_sent = True
        except discord.Forbidden as exc:
            self._log_http_error(
                "send public reminder",
                exc,
                channel_id=getattr(message.channel, "id", None),
            )
        except discord.NotFound as exc:
            self._log_http_error(
                "send public reminder",
                exc,
                channel_id=getattr(message.channel, "id", None),
            )
        except discord.HTTPException as exc:
            self._log_http_error(
                "send public reminder",
                exc,
                channel_id=getattr(message.channel, "id", None),
            )

        if organizer is not None:
            confirmation = (
                f"Reminder process for '{game_title}' complete.\n"
                f"- Sent {sent_count} reminder DMs."
            )
            if failed_count:
                confirmation += (
                    f" Failed to send {failed_count} DMs (users may have DMs disabled or blocked)."
                )
            if channel_reminder_sent:
                confirmation += "\n- A public reminder was sent to the event channel."
            else:
                confirmation += "\n- Failed to send a public reminder to the event channel."
            await self._safe_dm(organizer, confirmation, "send reminder confirmation DM")

        await self._remove_reaction(message, emoji, organizer)
